### ISSUE TITLE
PHP UNIT test triggers error

### ISSUE THREAD

**Issue by rezeau** [moodleou/moodle-qtype_oumultiresponse#12]
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.
........F................                                         25 / 25 (100%)
There was 1 failure:
1) qtype_oumultiresponse_question_test::test_grade_computation
Failed asserting that 0.3333333 matches expected 0.33333333333333331.

**Comment by timhunt** [comment]
I think this is fixed in the latest version. Certainly the tests passed on github actions, so marking this doen.
