### ISSUE TITLE
Bug: Checkmarks are placed within the text

### ISSUE THREAD

**Issue by Kathrin84** [moodleou/moodle-qtype_oumultiresponse#8]
Hi,

in Moodle 3.5 the checkmarks the user sees after his answers have been validated do not have an margin and they are place within the text:
![ou_multi_bc](https://user-images.githubusercontent.com/4711883/43505419-2d6feee2-9567-11e8-827f-ad8dc85fd457.png)

A possible solution is to add a margin to the icon:
```
.oumultiresponse.deferredfeedback .icon {
	margin-left: 1rem;
}
```

Best, Kathrin

**Comment by timhunt** [comment]
Thank you very much for reporting this problem.

In fact, I went for a slighly different fix, based on what they did for qtype_multichoice in Moodle core.
